
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_demo_db
    password: 1
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      enabled: true

server:
  servlet:
    context-path: /api
